#!/usr/bin/env bash
# Push from client a file
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo /etc/init.d/nginx start
