#!/usr/bin/env bash
# Create a custom 404 page that contains a string
sudo apt-get update
sudo apt-get install -y nginx
echo "Holberton School my people" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/error_404.html
sudo sed -i '/listen 80 default_server/a error_page 404 /error_404.html; location = /error_404.html {root /usr/share/nginx/html;\n internal;}' /etc/nginx/sites-available/default
sudo service nginx restart
