#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
trap interrup SIGTERM

interrup()
{
    echo "I am invincible!!!"
}

while true
do
    echo "To infinity and beyond"
    sleep 2
done
