#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
i=10
while [ "$i" -gt 0 ]
do
    echo "Holberton School"
    if [ "$i" -eq 2 ]
    then
        echo "Hi"
    fi
    i=$((i - 1))
done
i=$i
